# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'd4498e39-edbd-4b41-9e7b-2f4748cd66d7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rgg'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName MyProject -linkedTemplateUri https://raw.githubusercontent.com/manuelrb98/AzureRmPipeline-repo/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'MyDeployPipelineTemplate'